on:
  push:
    branches:
      - main

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Install DocFX
      run: dotnet tool update -g docfx

    - name: Generate metadata
      working-directory: ./DocumentationTest
      run: docfx metadata docfx.json

    - name: Build documentation
      working-directory: ./DocumentationTest
      run: docfx build docfx.json

    - name: Generate PDF
      working-directory: ./DocumentationTest
      run: docfx pdf docfx.json

    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload the generated site folder
        path: 'DocumentationTest/_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
